package cn.yxl.bx.pojo;

// Generated 2017-12-5 10:32:31 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * BxDept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

	private Integer deptno;
	private String dname;
	private String status;
	private Integer parentid;

	public Dept() {
	}

	public Dept(String dname, String status, Integer parentid) {
		this.dname = dname;
		this.status = status;
		this.parentid = parentid;
	}

	public Integer getDeptno() {
		return this.deptno;
	}

	public void setDeptno(Integer deptno) {
		this.deptno = deptno;
	}

	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

}
