package cn.yxl.bx.pojo;

// Generated 2017-12-5 10:32:31 by Hibernate Tools 4.0.0

/**
 * BxPersonalVip generated by hbm2java
 */
public class PersonalVip implements java.io.Serializable {

	private Integer perid;
	private VipUser vipUsers;
	private String card;
	private String realname;
	private String cardPic;
	private String address;
	private String mobile;
	private String email;
	private String tablePhone;
	private String personalStatus;
	private String style;

	public PersonalVip() {
	}

	public PersonalVip(Integer perid, VipUser vipUsers, String card,
			String realname, String cardPic, String address, String mobile,
			String email, String tablePhone, String personalStatus, String style) {
		super();
		this.perid = perid;
		this.vipUsers = vipUsers;
		this.card = card;
		this.realname = realname;
		this.cardPic = cardPic;
		this.address = address;
		this.mobile = mobile;
		this.email = email;
		this.tablePhone = tablePhone;
		this.personalStatus = personalStatus;
		this.style = style;
	}

	public Integer getPerid() {
		return this.perid;
	}

	public void setPerid(Integer perid) {
		this.perid = perid;
	}

	public VipUser getVipUsers() {
		return vipUsers;
	}

	public void setVipUsers(VipUser vipUsers) {
		this.vipUsers = vipUsers;
	}

	public String getCard() {
		return this.card;
	}

	public void setCard(String card) {
		this.card = card;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getCardPic() {
		return this.cardPic;
	}

	public void setCardPic(String cardPic) {
		this.cardPic = cardPic;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTablePhone() {
		return this.tablePhone;
	}

	public void setTablePhone(String tablePhone) {
		this.tablePhone = tablePhone;
	}

	public String getPersonalStatus() {
		return this.personalStatus;
	}

	public void setPersonalStatus(String personalStatus) {
		this.personalStatus = personalStatus;
	}

	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

}
