package cn.yxl.bx.pojo;

import java.util.List;

// Generated 2017-12-5 10:32:31 by Hibernate Tools 4.0.0

/**
 * BxRole generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer roleid;
	private String roleCn;
	private String roleEn;
	private Integer parentid;
	private String status;
	private List<Priciliage> prilist;

	public Role() {
	}

	public Role(String roleCn, String roleEn, Integer parentid, String status) {
		this.roleCn = roleCn;
		this.roleEn = roleEn;
		this.parentid = parentid;
		this.status = status;
	}

	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	public String getRoleCn() {
		return this.roleCn;
	}

	public void setRoleCn(String roleCn) {
		this.roleCn = roleCn;
	}

	public String getRoleEn() {
		return this.roleEn;
	}

	public void setRoleEn(String roleEn) {
		this.roleEn = roleEn;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public List<Priciliage> getPrilist() {
		return prilist;
	}

	public void setPrilist(List<Priciliage> prilist) {
		this.prilist = prilist;
	}

}
