package cn.yxl.bx.pojo;

// Generated 2017-12-5 10:32:31 by Hibernate Tools 4.0.0

/**
 * BxVipUsers generated by hbm2java
 */
public class VipUser implements java.io.Serializable {

	private Integer userid;
	private Area area;
	private String loginname;
	private String loginpwd;
	private String mobile;
	private String nickname;
	private String picpath;
	private String email;
	private String address;
	private String userStatus;

	public VipUser() {
	}

	public VipUser(Area area, String loginname, String loginpwd,
			String mobile, String nickname, String picpath, String email,
			String address, String userStatus) {
		this.area = area;
		this.loginname = loginname;
		this.loginpwd = loginpwd;
		this.mobile = mobile;
		this.nickname = nickname;
		this.picpath = picpath;
		this.email = email;
		this.address = address;
		this.userStatus = userStatus;

	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getLoginpwd() {
		return this.loginpwd;
	}

	public void setLoginpwd(String loginpwd) {
		this.loginpwd = loginpwd;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPicpath() {
		return this.picpath;
	}

	public void setPicpath(String picpath) {
		this.picpath = picpath;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

}
